/* 
**  mod_notes.c -- Apache sample notes module
**  [Autogenerated via ``apxs -n notes -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_notes.c
**
**  Then activate it in Apache's httpd.conf file for instance
**  for the URL /notes in as follows:
**
**    #   httpd.conf
**    LoadModule notes_module modules/mod_notes.so
**    <Location /notes>
**      SetOutputFilter NOTE_FILTER
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
*/ 

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"
#include "http_log.h"

static apr_status_t note_output_filter(ap_filter_t *f, apr_bucket_brigade *in_bb) {
    static const char *note = "NOTE";
    static const int  note_length = 4;
    const char *c = NULL;
    int i;
    request_rec *r = f->r;
    const apr_array_header_t *arr = apr_table_elts(r->headers_out);
    apr_table_entry_t *elts = (apr_table_entry_t *)arr->elts;
    for (i = 0; i < arr->nelts; i++) {
        c = elts[i].key;
        if (c != NULL && strlen(c) > note_length) {
            if (strncmp(note, c, note_length) == 0) {
                apr_table_set(r->notes, c, elts[i].val);
                //apr_table_unset(r->headers_out, c);
            }
        }      
    }
    // fix me
    int is_end = 1;
    do {
      is_end = 1;
      for (i = 0; i < arr->nelts; i++) {
          c = elts[i].key;
          if (c != NULL && strlen(c) > note_length) {
              if (strncmp(note, c, note_length) == 0) {
                  apr_table_unset(r->headers_out, c);
                  is_end = 0;
              }
          }
      }
    } while(!is_end);
    return ap_pass_brigade(f->next, in_bb);
}


static void notes_register_hooks(apr_pool_t *p) {
    ap_register_output_filter("NOTE_FILTER", note_output_filter, NULL, AP_FTYPE_RESOURCE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA notes_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    NULL,                  /* table of config file commands       */
    notes_register_hooks   /* register hooks                      */
};

